// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Minimal FRB-exposed API to validate toolchain
Future<String> torHelloFrb() => RustLib.instance.api.crateBridgeTorHelloFrb();

/// Start Tor service
///
/// If use_system_proxy is true, Tor will use the proxy set via tor_set_proxy_frb().
/// If false or no proxy is set, direct connections will be used.
Future<int> torStartFrb(
        {required int socksPort,
        required String stateDir,
        required String cacheDir,
        required bool useSystemProxy}) =>
    RustLib.instance.api.crateBridgeTorStartFrb(
        socksPort: socksPort,
        stateDir: stateDir,
        cacheDir: cacheDir,
        useSystemProxy: useSystemProxy);

/// Update current proxy configuration
///
/// Pass None to clear proxy (use direct connection).
/// Pass Some(ProxyInfo) to set/update proxy.
///
/// This can be called while Tor is running to update proxy dynamically.
Future<void> torSetProxyFrb({ProxyInfo? proxy}) =>
    RustLib.instance.api.crateBridgeTorSetProxyFrb(proxy: proxy);

/// Stop Tor service
Future<void> torStopFrb() => RustLib.instance.api.crateBridgeTorStopFrb();

/// Set dormant mode
Future<void> torSetDormantFrb({required bool softMode}) =>
    RustLib.instance.api.crateBridgeTorSetDormantFrb(softMode: softMode);

/// Proxy information passed from Dart
class ProxyInfo {
  final String address;
  final int port;
  final ProxyType proxyType;
  final String? username;
  final String? password;

  const ProxyInfo({
    required this.address,
    required this.port,
    required this.proxyType,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      port.hashCode ^
      proxyType.hashCode ^
      username.hashCode ^
      password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          port == other.port &&
          proxyType == other.proxyType &&
          username == other.username &&
          password == other.password;
}

/// Proxy type enumeration
enum ProxyType {
  socks5,
  httpConnect,
  ;
}
